/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StokRouteImport } from './routes/stok'
import { Route as LossProfitRouteImport } from './routes/loss-profit'
import { Route as LaporanTahunanRouteImport } from './routes/laporan-tahunan'
import { Route as LaporanAnggotaRouteImport } from './routes/laporan-anggota'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as AnggotaRouteImport } from './routes/anggota'
import { Route as IndexRouteImport } from './routes/index'

const StokRoute = StokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => rootRouteImport,
} as any)
const LossProfitRoute = LossProfitRouteImport.update({
  id: '/loss-profit',
  path: '/loss-profit',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanTahunanRoute = LaporanTahunanRouteImport.update({
  id: '/laporan-tahunan',
  path: '/laporan-tahunan',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanAnggotaRoute = LaporanAnggotaRouteImport.update({
  id: '/laporan-anggota',
  path: '/laporan-anggota',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaRoute = AnggotaRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
  '/laporan': typeof LaporanRoute
  '/laporan-anggota': typeof LaporanAnggotaRoute
  '/laporan-tahunan': typeof LaporanTahunanRoute
  '/loss-profit': typeof LossProfitRoute
  '/stok': typeof StokRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
  '/laporan': typeof LaporanRoute
  '/laporan-anggota': typeof LaporanAnggotaRoute
  '/laporan-tahunan': typeof LaporanTahunanRoute
  '/loss-profit': typeof LossProfitRoute
  '/stok': typeof StokRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
  '/laporan': typeof LaporanRoute
  '/laporan-anggota': typeof LaporanAnggotaRoute
  '/laporan-tahunan': typeof LaporanTahunanRoute
  '/loss-profit': typeof LossProfitRoute
  '/stok': typeof StokRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anggota'
    | '/laporan'
    | '/laporan-anggota'
    | '/laporan-tahunan'
    | '/loss-profit'
    | '/stok'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anggota'
    | '/laporan'
    | '/laporan-anggota'
    | '/laporan-tahunan'
    | '/loss-profit'
    | '/stok'
  id:
    | '__root__'
    | '/'
    | '/anggota'
    | '/laporan'
    | '/laporan-anggota'
    | '/laporan-tahunan'
    | '/loss-profit'
    | '/stok'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnggotaRoute: typeof AnggotaRoute
  LaporanRoute: typeof LaporanRoute
  LaporanAnggotaRoute: typeof LaporanAnggotaRoute
  LaporanTahunanRoute: typeof LaporanTahunanRoute
  LossProfitRoute: typeof LossProfitRoute
  StokRoute: typeof StokRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stok': {
      id: '/stok'
      path: '/stok'
      fullPath: '/stok'
      preLoaderRoute: typeof StokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loss-profit': {
      id: '/loss-profit'
      path: '/loss-profit'
      fullPath: '/loss-profit'
      preLoaderRoute: typeof LossProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan-tahunan': {
      id: '/laporan-tahunan'
      path: '/laporan-tahunan'
      fullPath: '/laporan-tahunan'
      preLoaderRoute: typeof LaporanTahunanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan-anggota': {
      id: '/laporan-anggota'
      path: '/laporan-anggota'
      fullPath: '/laporan-anggota'
      preLoaderRoute: typeof LaporanAnggotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota': {
      id: '/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof AnggotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnggotaRoute: AnggotaRoute,
  LaporanRoute: LaporanRoute,
  LaporanAnggotaRoute: LaporanAnggotaRoute,
  LaporanTahunanRoute: LaporanTahunanRoute,
  LossProfitRoute: LossProfitRoute,
  StokRoute: StokRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
